//import Components
import UploadButton from "../components/upload-button";

export default function MainHeader({ ChangeHandler }) {
  return (
    <div id="header" className="min-h-[300px] bg-gray-500 text-white mb-7">
      <div className="flex flex-wrap px-5">
        <div className="md:max-w-1/2 md:p-[5%]">
          <h1 className="font-bold md:text-2xl">
            Convert RankMath Redirects to next.js
          </h1>
          <p className="text-sm mb-4">
            This is a simple Tool build in next.js, which will help you to
            convert your Redirects your redirects generated by the RankMath
            Plugin for WordPress to your next.js Application file. Check the
            Documentation for full instructions in how to use this application.
          </p>
          <ol className="text-sm pl-7 list-decimal">
            <li>Export RankMath Redirections</li>
            <li>Upload .csv file</li>
            <li>Import the converted code into your next.config.js</li>
          </ol>
        </div>
        <div className="flex flex-wrap justify-center md:max-w-1/2 md:p-[5%]">
          <UploadButton ChangeHandler={ChangeHandler} />
        </div>
      </div>
    </div>
  );
}
