import Head from "next/head";

export default function howtouse () {
    return (
        <div>
            <Head>
                <title>How to convert your WorPress Redirects from WordPress to next.js - wpToNext</title>
                <meta charSet="utf-8" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                <meta name="description" content="Learn how to use wpToNext to convert your WordPress redirects generated by RankMath or YoastSEO to next.js in seconds." />
            </Head>
            <h1>How to use</h1>
        </div>
    );
}